sudo: required
services:
  - docker

before_install:
  - docker build -t biphy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true biphy/react-test npm test

after_success:
  - docker build -t biphy/multi-client ./client
  - docker build -t biphy/multi-nginx ./nginx
  - docker build -t biphy/multi-server ./server
  - docker build -t biphy/multi-worker ./worker
  # Log in to hub.docker.com
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push biphy/multi-client
  - docker push biphy/multi-nginx
  - docker push biphy/multi-server
  - docker push biphy/multi-worker
